name: $(BuildID)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
resources:
- repo: self
  clean: true
phases:
- phase: linux
  variables:
    _PREVIEW_VSTS_DOCKER_IMAGE: "aziotbld/linux-c-ubuntu-16.04:latest"
  queue: aziotbld-lin01
  displayName: 'dynamic'
  steps:
  - script: 'sudo ./script/execute_analysis.sh'
  - task: DeleteFiles@1
    displayName: 'Delete files from $(Agent.BuildDirectory)'
    inputs:
      SourceFolder: '$(Agent.BuildDirectory)'
    condition: always()
